/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment2;

import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;

/**
 *
 * @author MAHAMED ABDI
 */
public class RadioBtnAss extends javax.swing.JFrame {

    /**
     * Creates new form RadioBtnAss
     */
    public RadioBtnAss() {
        initComponents();
        groupRadioButtons(); 
    }
    private void groupRadioButtons() {
        ButtonGroup buttonGroup = new ButtonGroup();
        buttonGroup.add(Birdbtn);
        buttonGroup.add(Dogbtn);
        buttonGroup.add(Owlbtn);
        buttonGroup.add(Pigbtn);
        buttonGroup.add(Rabbitbtn);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Birdbtn = new javax.swing.JRadioButton();
        Owlbtn = new javax.swing.JRadioButton();
        Dogbtn = new javax.swing.JRadioButton();
        Pigbtn = new javax.swing.JRadioButton();
        Rabbitbtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Birdbtn.setText("Bird");
        Birdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdbtnActionPerformed(evt);
            }
        });

        Owlbtn.setText("Owl");
        Owlbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwlbtnActionPerformed(evt);
            }
        });

        Dogbtn.setText("Dog");
        Dogbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogbtnActionPerformed(evt);
            }
        });

        Pigbtn.setText("Pig");
        Pigbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PigbtnActionPerformed(evt);
            }
        });

        Rabbitbtn.setText("Rabbit");
        Rabbitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabbitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Pigbtn)
                        .addComponent(Dogbtn)
                        .addComponent(Birdbtn)
                        .addComponent(Owlbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(Rabbitbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Birdbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dogbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Owlbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pigbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rabbitbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BirdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdbtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/bird.jpeg")));
    }//GEN-LAST:event_BirdbtnActionPerformed

    private void DogbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogbtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/dog.jpeg")));
    }//GEN-LAST:event_DogbtnActionPerformed

    private void OwlbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwlbtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/owl.jpeg")));
    }//GEN-LAST:event_OwlbtnActionPerformed

    private void PigbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PigbtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/pig.jpeg")));
    }//GEN-LAST:event_PigbtnActionPerformed

    private void RabbitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabbitbtnActionPerformed
        // TODO add your handling code here:
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/images/rabbit.jpeg")));
    }//GEN-LAST:event_RabbitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioBtnAss().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Birdbtn;
    private javax.swing.JRadioButton Dogbtn;
    private javax.swing.JRadioButton Owlbtn;
    private javax.swing.JRadioButton Pigbtn;
    private javax.swing.JRadioButton Rabbitbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
